-- Localization by @xphrogx on discord
return {
	descriptions = {
		Joker = {
			j_mp_defensive_joker = {
				name = "Defensive Joker",
				text = {
					"This Joker gains {C:chips}+#1#{} Chips",
					"per {C:red,E:1}life{} lost this run",
					"{C:inactive}(Currently {C:chips}+#2#{C:inactive} Chips)",
				},
			},
			j_mp_skip_off = {
				name = "Skip-Off",
				text = {
					"{C:blue}+#1#{} Hände und {C:red}+#2#{} Abwürfe",
					"pro zusätzliche {C:attention}Blind{} die übersprungen wurde",
					"im vergleich zu deinen {X:purple,C:white}Erzfeind{}",
					"{C:inactive}(Zurzeit {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive})",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Lets Go Gambling",
				text = {
					"Wenn verkauft, {C:green}#1# in #2#{} chance zu",
					"verschwinden,  {X:mult,C:white} +X#3# {}",
					"{C:inactive}(Skalierung erhöht sich um {X:mult,C:white}+X#4#{C:inactive} nach jeder {C:attention}Boss Blind{C:inactive})",
					"{C:inactive}(Zurzeit {X:mult,C:white}X#5#{C:inaktive} Mult)",
				},
			},
			j_mp_hanging_bad = {
				name = "Hanging Bad",
				text = {
					"Während {X:purple,C:white}Erzfeind{} {C:attention}Blinds{} ist die",
					"{C:attention}erste{} gespielte karte während der punktezählung",
					" {C:attention}	Geschwächt{} fϋr beide spieler",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"When du alle deine {C:blue}Hānde{} vor",
					"deinem {X:purple,C:white}Gegner{} benutzt in einem {C:attention}PvP Blind{},",
					"{C:attention}verdreifache{} deine gesamte Punktzahl",
				},
			},
			j_broken = {
				name = "Defekt",
				text = {
					"Diese Karte is entweder",
					"defekt oder nicht verfügbar in der",
					"Version der Mod die benutzt wird.",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroid",
				text = {
					"Entferne #1# level Von",
					"Dein {X:purple,C:white}Gegners'{}",
					"Höchste verbesserte",
					"{C:legendary,E:1}Poker Hand{}",
				},
			},
		},
		Blind = {
			bl_pvp = {
				name = "Dein Erzfeind",
				text = {
					"Spiel gegen dein Erzfeind,",
					"Höste Punktzahl gewinnt",
				},
			},
			bl_precision = {
				name = "Präzision",
				text = {
					"Spiel gegen ein spieler,",
					"Spieler am nähesten zu der ziel punktzahl gewinnt",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Erzfeind",
				text = {
					"{X:purple,C:white}#1#{}",
					"Dein größter und einziger Erzfein",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Mehrspieler",
		},
		dictionary = {
			singleplayer = "Einzelspieler",
			join_lobby = "Lobby beitreten",
			return_lobby = "Zurück zur lobby",
			reconnect = "Widerverbinden",
			create_lobby = "Lobby herstellen",
			start_lobby = "Lobby starten",
			enemy_score = "Dein Gegners Punktzahl",
			enemy_hands = "Gegners übrige Hände: ",
			coming_soon = "Kommt bald!",
			ready = "Bereit",
			unready = "Nicht bereit",
			wait_enemy = "Warte auf dein Gegner...",
			lives = "Leben",
			leave_lobby = "Lobby verlassen",
			lost_life = "Ein leben verloren",
			failed = "Verloren",
			defeat_enemy = "Gegner besiegt",
			total_lives_lost = "Gesamtzahl an verloren Leben ($4 Pro Leben)",
			attrition_name = "Standard",
			attrition_desc = "Jeder Boss Blind is ein kampf gegen deine Gegner. Wer die niedrigste Punktzahl hat verliert ein Leben",
			-- New stuff here
			showdown_name = "Showdown",
			showdown_desc = "Beide spieler spielen 3 Antes, dann spielen sie eine Ante wo jede Runde der Spieler mit der hösten Punktzahl gewinnt.",
			draft_name = "Draft",
			draft_desc = "Spieler spielen das Evolving Deck von der Balatro Draft mod, wo sie beide einen Draft tag bekommen nach jeden Pvp Blind.",
			draft_req = "Benötigt die Balatro Draft Mod",
			monty_special_name = "Das Dr. Monty Special",
			monty_special_desc = "Ein spielmodus erstellt bei @dr_monty_the_snek von dem discord server. Scheinbar musst du selber rausfinden was es ist! (Spielmodus ändert sich mit jeden kleinen update)",
			precision_name = "Präzision",
			precision_desc = "Das selbe wie Standard, aber die person die am nähesten an der ziel punktzahl ist gewinnt denn Pvp Blind (statt der person mit der höchsten punkzahl).",
			-- New stuff ends here
			royale_name = "Battle Royale",
			royale_desc = "Standard, aber ihr seid bis zu 8 Spieler und jeder hat nur 1 Leben.",
			vanilla_plus_name = "Vanilla+",
			vp_desc = "Der Erste spieler der eine rounde verliert verliert das spiel, keine PvP Blinds.",
			enter_lobby_code = "Lobby Code eingeben",
			join_clip = "Einfügen von der Zwischenablage",
			username = "Benutzername:",
			enter_username = "Benutzername eingeben",
			join_discord = "Finde uns im",
			discord_name = "Balatro Mehrspieler Discord Server",
			discord_msg = "Du kannst Bugs hier reporten und andere Mitspieler finden",
			enter_to_save = "Drück Enter zum speichern",
			in_lobby = "In Der Lobby",
			connected = "Verbindung zum Service hergestellt",
			warn_service = "WARNUNG: Mehrspieler service konnte nicht gefunden werden",
			set_name = "Setz dein Benutzername in der Config im Hauptmenü! (Mods > Multiplayer > Config)",
			start = "START",
			wait_for = "WARTE AUF",
			host_start = "DEN HOST",
			players = "ANDERE SPIELER",
			lobby_options_cap = "LOBBY OPTIONEN",
			lobby_options = "Lobby Optionen",
			copy_clipboard = "Zur Zwischenablage kopieren",
			connect_player = "Verbundene Spieler:",
			view_code = "CODE ZEIGEN",
			leave = "VERLASSEN",
			opts_only_host = "Nur der Host kann diese Einstellungen ändern",
			opts_cb_money = "Gib comeback $ wenn ein Leben verloren ist",
			opts_no_gold_on_loss = "Gib keine Blind Belohnung wenn eine runde verloren wurde",
			opts_death_on_loss = "Verlier ein Leben wehnn eine nicht-PvP runde verloren wurde",
			opts_start_antes = "Starter Antes",
			opts_diff_seeds = "Spieler haben unterschiedliche seeds",
			opts_lives = "Leben",
			opts_gm = "Spiel Modifikationen",
			bl_or = "oder",
			bl_life = "Leben",
			bl_death = "Sterben",
			lobby = "Lobby",
			return_to = "Zurück zur",
			enemy_loc_1 = "Gegner",
			enemy_loc_2 = "Standort",
			loc_ready = "Bereit für PvP",
			loc_selecting = "Eine Blind am auswählen",
			loc_shop = "Einkaufen",
			loc_playing = "Spielen",
			current_seed = "Aktueller seed: ",
			random = "Zufällig",
			reset = "Neustart",
			set_custom_seed = "Setzt eigenen Seed fest",
			mod_hash_warning = "Spieler haben andere Mods oder unterschidliche Mod versionen! Dies kann probleme verursachen!",
			-- New stuff here
			lobby_choose_deck = "DECK",
			opts_player_diff_deck = "Spieler haben andere decks ",
		},
	},
}
