-- Localization by @panbimbogd on discord
return {
	Joker = {
		j_broken = {
			name = "ROTA",
			text = {
				"Esta carta está rota o no está",
				"implementada en la versión actual",
				"de un mod que estás usando.",
			},
		},
	},
	descriptions = {
		Blind = {
			bl_pvp = {
				name = "Tu Némesis",
				text = {
					"Enfrentándote a otros jugadores,",
					"mas fichas gana",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Multijugador",
		},
		dictionary = {
			singleplayer = "Un jugador",
			join_lobby = "Entrar a la Lobby",
			return_lobby = "Volver a la lobby",
			reconnect = "Reconectarse",
			create_lobby = "Crear Lobby",
			start_lobby = "Iniciar Lobby",
			enemy_score = "Puntuación actual del enemigo",
			enemy_hands = "Manos restantes del enemigo: ",
			coming_soon = "Muy pronto!",
			ready = "Listo",
			unready = "No listo",
			wait_enemy = "Esperando a que el enemigo termine...",
			lives = "Vidas",
			leave_lobby = "Abandonar la Lobby",
			lost_life = "Pierde una vida",
			failed = "Fallido",
			defeat_enemy = "Enemigo Derrotado",
			total_lives_lost = " Vidas totales perdidos ($4 cada una)",
			attrition_name = "Desgaste",
			attrition_desc = "Cada ronda de jefe es una competición entre jugadores donde el jugador con la puntuación más baja pierde una vida.",
			draft_name = "Draft",
			draft_desc = "Ambos jugadores juegan 3 antes normales, luego juegan un ante donde en cada ronda gana el jugador con mayor puntuación.",
			royale_name = "Battle Royale",
			royale_desc = "Desgaste, excepto que hay hasta 8 jugadores y cada jugador solo tiene 1 vida.",
			vanilla_plus_name = "Vanilla+",
			vp_desc = "La primera persona que falle una ronda pierde, no hay ciegas en PvP.",
			enter_lobby_code = "Escribe el Código de la Lobby",
			join_clip = "Pega desde el portapapeles",
			username = "Nombre de usuario:",
			enter_username = "Escribir nombre de usuario",
			join_discord = "Entra en el ",
			discord_name = "Servidor de Discord de Balatro Multiplayer",
			discord_msg = "Allí puedes reportar bugs y encontrar personas con las que jugar",
			enter_to_save = "Presiona INTRO para guardar",
			in_lobby = "En la Lobby",
			connected = "Conectado al servicio",
			warn_service = "ADVERTENCIA: No se ha podido encontrar servicio Multijugador",
			set_name = "Especifíca tu nombre de usuario en el menú principal! (Mods > Multiplayer)",
			start = "INICAR",
			wait_for = "ESPERANDO POR",
			host_start = "EL ANFITRIÓN",
			players = "JUGADORES",
			lobby_options_cap = "OPCIONES DE LOBBY",
			lobby_options = "Opciones de Lobby",
			copy_clipboard = "Copiar al portapapeles",
			connect_player = "Jugadores conectados:",
			view_code = "VER CÓDIGO",
			leave = "SALIR",
			opts_only_host = "Solo el anfitrión puede cambiar estas opciones",
			opts_cb_money = "Recibe oro al perder una vida para ayudarte a remontar",
			opts_no_gold_on_loss = "No te quedas con el oro de la ciega si pierdes una ronda",
			opts_death_on_loss = "Se pierden vidas en rondas no PvP",
			opts_start_antes = "Iniciando Antes",
			opts_diff_seeds = "Los jugadores tienen diferentes semillas",
			opts_lives = "Vidas",
			opts_gm = "Modificadores de juego",
			bl_or = "o",
			bl_life = "Vida",
			bl_death = "Muerte",
			lobby = "Lobby",
			return_to = "Vuelve a la",
			enemy_loc_1 = "enemigo",
			enemy_loc_2 = "Ubicación del",
			loc_ready = "Listo para el PvP",
			loc_selecting = "Seleccionando una ciega",
			loc_shop = "Comprando",
			loc_playing = "Enfrentandose a ",
			current_seed = "Semilla actual: ",
			random = "Aleatoria",
			set_custom_seed = "Semilla personalizada",
			reset = "Resetear",
			mod_hash_warning = "¡Los jugadores tienen diferentes mods o diferentes versiones de mods! ¡Esto puede causar problemas!",
		},
		v_dictionary = {
			mp_art = { "Arte: #1#" },
			mp_code = { "Código: #1#" },
			mp_idea = { "Idea: #1#" },
		},
	},
}
