return {
	descriptions = {
		Joker = {
			j_mp_defensive_joker = {
				name = "Joker Défensif",
				text = {
					"Ce Joker gagne {C:chips}+#1#{} Jetons",
					"par {C:red,E:1}vie{} perdue cette partie",
					"{C:inactive}(Actuellement {C:chips}+#2#{C:inactive} Jetons)",
				},
			},
			j_mp_skip_off = {
				name = "Marelle",
				text = {
					"{C:blue}+#1#{} Mains et {C:red}+#2#{} Défausses",
					"par {C:attention}Blinde{} passée",
					"{C:attention}de plus{} que votre {X:purple,C:white}Némésis{}",
					"{C:inactive}(Actuellement {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive})",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Machine à Sous",
				text = {
					"Quand ce Joker est vendu, il y a {C:green}#1# chance(s) sur #2#{}",
					"qu'il soit détruit, sinon octroie {X:mult,C:white} +X#3# {} multi",
					"{C:inactive}(Augmente de {X:mult,C:white}+X#4#{C:inactive} après chaque {C:attention}Blinde Boss{C:inactive})",
					"{C:inactive}(Actuellement {X:mult,C:white}X#5#{C:inactive} Multi)",
				},
			},
			j_mp_hanging_bad = {
				name = "Abstention",
				text = {
					"Pendant les {C:attention}Blindes PvP{} contre votre {X:purple,C:white}Némésis{},",
					"la {C:attention}première{} carte marquant des points",
					"est {C:attention}affaiblie{} pour les deux joueurs",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"Si toutes vos {C:blue}Mains{} sont utilisées avant",
					"votre {X:purple,C:white}Némésis{} durant une {C:attention}Blinde PvP{},",
					"votre score total est {C:attention}triplé.{}",
				},
			},
			j_broken = {
				name = "CASSÉ",
				text = {
					"Cette carte est cassée, ou elle n'est",
					"pas implémentée dans une version",
					"actuelle d'un mod que vous utilisez.",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Astéroïde",
				text = {
					"Retire #1# niveau",
					"à la {C:legendary,E:1}main de poker{}",
					"la plus améliorée",
					"de votre {X:purple,C:white}Némésis{}",
				},
			},
		},
		Blind = {
			bl_pvp = {
				name = "Votre Némésis",
				text = {
					"Jouez contre un.e autre joueur.se,",
					"le plus grand nombre de jetons marqués gagne.",
				},
			},
			bl_precision = {
				name = "Précision",
				text = {
					"Jouez contre un.e autre joueur.se,",
					"le score le plus proche de la cible gagne.",
				},
			},
		},
		Edition = {
			e_mp_phantom = {
				name = "Fantôme",
				text = {
					"{C:attention}Éternel{} et {C:dark_edition}Négatif{}",
					"Créé et détruit par votre {X:purple,C:white}Némésis{}",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Votre Némésis",
				text = {
					"{X:purple,C:white}#1#{}",
					"Votre seul et unique ennemi.",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Multijoueur",
		},
		dictionary = {
			singleplayer = "Solo",
			join_lobby = "Rejoindre un Lobby",
			return_lobby = "Retourner au Lobby",
			reconnect = "Se Reconnecter",
			create_lobby = "Créer un Lobby",
			start_lobby = "Créer le Lobby",
			enemy_score = "Score ennemi actuel",
			enemy_hands = "Mains ennemies restantes: ",
			coming_soon = "Bientôt!",
			ready = "Prêt",
			unready = "Pas Prêt",
			wait_enemy = "En attente de l'ennemi...",
			lives = "Vies",
			leave_lobby = "Quitter le Lobby",
			lost_life = "A perdu une vie",
			failed = "Échec",
			defeat_enemy = "A Vaincu l'Ennemi",
			total_lives_lost = " Total de Vies Perdues ($4 chacune)",
			attrition_name = "Érosion",
			attrition_desc = "A chaque blinde boss, les deux joueurs s'affrontent. Le joueur faisant le score le moins élevé perd une vie.",
			showdown_name = "Face-à-Face",
			showdown_desc = "Les deux joueurs jouent 3 mises initiales normales, puis une mise initiale où à chaque manche, le joueur avec le meilleur score gagne.",
			draft_name = "Draft",
			draft_desc = "Jouez le Deck Évolutif tiré du mod Balatro Draft, où chacun des joueurs obtient un Badge Draft après chaque Blinde PvP.",
			draft_req = "Nécessite le mod Balatro Draft",
			monty_special_name = "La Spéciale de Dr. Monty",
			monty_special_desc = "Un mode de jeu spécial créé par @dr_monty_the_snek du serveur Discord Balatro Multiplayer. Essayez par vous-même! (Le mode de jeu est modifié à chaque mise à jour mineure.)",
			precision_name = "Précision",
			precision_desc = "Similaire au mode Érosion, mais un score cible doit être atteint pour gagner (au lieu du score le plus élevé).",
			royale_name = "Battle Royale",
			royale_desc = "Comme Érosion, mais jusqu'à 8 joueurs qui n'ont chacun qu'une seule vie.",
			vanilla_plus_name = "Vanilla+",
			vp_desc = "La première personne perdant une manche perd la partie, pas de Blindes PvP.",
			enter_lobby_code = "Entrer Code du Lobby",
			join_clip = "Coller depuis presse-papiers",
			username = "Pseudo:",
			enter_username = "Entrer un pseudo",
			join_discord = "Rejoindre le ",
			discord_name = "Serveur Discord Balatro Multiplayer",
			discord_msg = "Vous pourrez y signaler des bugs et trouver des joueurs avec qui jouer",
			enter_to_save = "Appuyer sur Entrée pour sauvegarder",
			in_lobby = "Dans le lobby",
			connected = "Connecté au Service",
			warn_service = "WARN: Impossible de Trouver le Service Multijoueur",
			set_name = "Définissez votre pseudo dans le menu principal ! (Mods > Cliquer sur le mod Multiplayer > Config)",
			start = "COMMENCER",
			wait_for = "EN ATTENTE DE",
			host_start = "L'HÔTE POUR COMMENCER",
			players = "JOUEURS",
			lobby_options_cap = "OPTIONS DE LOBBY",
			lobby_options = "Options de Lobby",
			copy_clipboard = "Copier vers le presse-papiers",
			connect_player = "Joueurs connectés:",
			view_code = "VOIR LE CODE",
			leave = "QUITTER",
			opts_only_host = "Seul l'Hôte du Lobby peut changer ces options",
			opts_cb_money = "Obtenir des $ de dédommagement après avoir perdu une vie",
			opts_no_gold_on_loss = "Ne pas obtenir les récompenses de la Blinde après avoir perdu",
			opts_death_on_loss = "Perdre une vie après avoir perdu contre une Blinde non-PvP",
			opts_start_antes = "Mises initiales de Départ",
			opts_diff_seeds = "Graines différentes pour les joueurs",
			opts_lives = "Nombre de vies",
			opts_gm = "Options du Mode de Jeu",
			bl_or = "ou",
			bl_life = "Vie",
			bl_death = "Mort",
			lobby = "Lobby",
			return_to = "Retourner au",
			enemy_loc_1 = "Position",
			enemy_loc_2 = "ennemie",
			loc_ready = "Prêt.e pour PvP",
			loc_selecting = "Sélectionne une Blinde",
			loc_shop = "Dans le magasin",
			loc_playing = "Joue ",
			current_seed = "Graine Actuelle: ",
			random = "Aléatoire",
			reset = "Réinitialiser",
			set_custom_seed = "Graine Personnalisée",
			mod_hash_warning = "Les joueurs n'ont pas les même mods/versions de mods! Cela peut causer des dysfonctionnements!",
			lobby_choose_deck = "CHOISIR UN DECK",
			opts_player_diff_deck = "Les joueurs peuvent avoir des decks différents",
		},
	},
}
