return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "エラー",
				text = {
					"このカードは現在使用しているMODのバージョンでは未実装、",
					"またはデータが壊れている可能性があります",
				},
			},
		},
		Blind = {
			bl_pvp = {
				name = "ライバル",
				text = {
					"スコアの高い方が勝ち！",
					"負けるとライフを1失う",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "マルチプレイ",
		},
		dictionary = {
			singleplayer = "シングルプレイ",
			join_lobby = "ロビーに参加",
			return_lobby = "ロビーに戻る",
			reconnect = "再接続",
			create_lobby = "ロビーの作成",
			start_lobby = "このモードで作成",
			enemy_score = "現在の相手のスコア",
			enemy_hands = "相手の残りハンド ",
			coming_soon = "Coming Soon!",
			ready = "準備OK!",
			unready = "解除",
			wait_enemy = "相手のプレイが終わるまでお待ちください...",
			lives = "ライフ",
			leave_lobby = "ロビーから退出",
			lost_life = "ライフ減少",
			failed = "失敗",
			defeat_enemy = "勝負あり！",
			total_lives_lost = "負けた回数 (1回につき$4)",
			attrition_name = "消耗戦",
			attrition_desc = "ボスブラインドは毎回プレイヤー同士のスコアアタックとなり、\nスコアが低いプレイヤーはライフを1失う。\n先にライフが0になった方が負け。",
			draft_name = "ドラフト",
			draft_desc = "お互いが通常通りにアンティ3までプレイした後、\n勝敗がつくまで毎ラウンドPvPブラインドをし続ける。\n(スコアアタックまでのアンティ数は設定で変更できます)",
			royale_name = "バトルロワイヤル",
			royale_desc = "最大8人でのバトルロワイヤル。ただしライフは1つだけ。",
			vanilla_plus_name = "バニラplus",
			vp_desc = "最初にゲームオーバーになった人が負け。(PvPブラインドなし。)",
			enter_lobby_code = "ロビーIDを入力",
			join_clip = "クリップボードからペースト",
			username = "ニックネーム:",
			enter_username = "ニックネームを入力",
			join_discord = "Balatro Multiplayer Discordサーバー",
			discord_name = "参加する",
			discord_msg = "バグ報告や対戦の申し込みはこちらから！",
			enter_to_save = "Enterで保存",
			in_lobby = "ロビー",
			connected = "接続済み",
			warn_service = "警告: マルチプレイヤーサービスが見つかりません。",
			set_name = "メインメニューからニックネームを設定してください！ (Mods > Multiplayer > Config)",
			start = "START",
			wait_for = "対戦相手を",
			host_start = "ゲームスタート",
			players = "待っています",
			lobby_options_cap = "カスタム設定",
			lobby_options = "設定",
			copy_clipboard = "クリップボードにコピー",
			connect_player = "参加者一覧",
			view_code = "ロビーIDの確認",
			leave = "ロビーから退出",
			opts_only_host = "オプションを変更できるのはホストのみです",
			opts_cb_money = "PvPブラインドで負けた場合に追加で$を受け取る",
			opts_no_gold_on_loss = "通常ラウンドでノルマ未達の場合にブラインド報酬を受け取らない",
			opts_death_on_loss = "通常ラウンドでノルマ未達の場合にライフを1失う",
			opts_start_antes = "PvP開始アンティ",
			opts_diff_seeds = "お互いに別シードでプレイ",
			opts_lives = "ライフ",
			opts_gm = "詳細設定",
			bl_or = "or",
			bl_life = "Life",
			bl_death = "Death",
			lobby = "",
			return_to = "ロビーに戻る",
			enemy_loc_1 = "相手の",
			enemy_loc_2 = "プレイ状況",
			loc_ready = "準備OK！",
			loc_selecting = "ブラインド選択",
			loc_shop = "SHOP",
			loc_playing = "",
			current_seed = "シード値: ",
			random = "ランダム",
			reset = "リセット",
			set_custom_seed = "シード値を指定",
			mod_hash_warning = "注意: 古いバージョンを利用しているため、場合によっては不具合が発生する可能性があります",
		},
	},
}
