-- Localization by @blablabla_c on discord
return {
	Joker = {
		j_broken = {
			name = "GEBROKEN",
			text = {
				"Deze kaart is gebroken of niet",
				"geïmplementeerd in de huidige versie",
				"van een mod die je gebruikt.",
			},
		},
	},
	descriptions = {
		Blind = {
			bl_pvp = {
				name = "Je Nemesis",
				text = {
					"Neem het op tegen een andere speler,",
					"meeste chips wint",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Multiplayer",
		},
		dictionary = {
			singleplayer = "Singleplayer",
			join_lobby = "Sluit je aan bij de lobby",
			return_lobby = "Ga terug naar lobby",
			reconnect = "Reconnect",
			create_lobby = "Creëer Lobby",
			start_lobby = "Start Lobby",
			enemy_score = "Huidige score van je vijand",
			enemy_hands = "Handen van vijand over: ",
			coming_soon = "Binnenkort Beschikbaar!",
			ready = "Klaar",
			unready = "Unready",
			wait_enemy = "Wacht op vijand om te eindigen...",
			lives = "Levens",
			leave_lobby = "Verlaat de Lobby",
			lost_life = "Leven verloren",
			failed = "Mislukt",
			defeat_enemy = "Vijand verslagen",
			total_lives_lost = " Aantal Levens Verloren ($4 elk)",
			attrition_name = "Standaard",
			attrition_desc = "Elke boss ronde is een competitie tussen spelers waarbij de speler met de laagste score een level verliest.",
			draft_name = "Draft",
			draft_desc = "Beide speleres spelen 3 normale antes, dan spelen ze een ante waarbij elke ronde de speler met de hoogste score wint.",
			royale_name = "Battle Royale",
			royale_desc = "Standaard, behalve dat er maximaal 8 spelers zijn en elke speler 1 leven heeft.",
			vanilla_plus_name = "Vanilla+",
			vp_desc = "De eerste persoon die een ronde niet haalt verliest, geen PvP Blinds.",
			headup_name = "Hoofd Omhoog",
			hu_desc = "Beide spelers spelen de eerste ante, dan moeten ze hun vijands laatste score verslaan, anders verliezen ze.",
			enter_lobby_code = "Voer de Lobby Code in",
			join_clip = "Plak Van Klembord",
			username = "Gebruikersnaam:",
			enter_username = "Voer gebruikersnaam in",
			join_discord = "Join de ",
			discord_name = "Balatro Multiplayer Discord Server",
			discord_msg = "Je kan daar eventuele bugs melden en kan er spelers vinden om tegen te spelen",
			enter_to_save = "Druk enter om op te slaan",
			in_lobby = "In de lobby",
			connected = "Verbonden met Service",
			warn_service = "WAARSCHUWING: Kan de multiplayer service niet vinden",
			set_name = "Verander je gebruikersnaam in het hoofdmenu! (Mods > Multiplayer > Config)",
			start = "START",
			wait_for = "WACHTEN OP",
			host_start = "HOST OM TE STARTEN",
			players = "SPELERS",
			lobby_options_cap = "LOBBY OPTIES",
			lobby_options = "Lobby Opties",
			copy_clipboard = "Kopieer naar klembord",
			connect_player = "Verbonden Spelers:",
			view_code = "BEKIJK CODE",
			leave = "VERLAAT",
			opts_only_host = "Enkel de Lobby Host kan deze opties veranderen",
			opts_cb_money = "Geef comeback $ bij levensverlies.",
			opts_no_gold_on_loss = "Krijg geen blind beloning op verlies van ronde",
			opts_death_on_loss = "Verlies een leven op non-PvP ronde verlies",
			opts_start_antes = "Beginnende Antes",
			opts_diff_seeds = "Spelers hebben verschillende seeds",
			opts_lives = "Levens",
			opts_gm = "Spelmodus Modificaties",
			bl_or = "of",
			bl_life = "Leven",
			bl_death = "Dood",
			lobby = "Lobby",
			return_to = "Ga terug naar",
			enemy_loc_1 = "Vijand",
			enemy_loc_2 = "locatie",
			loc_ready = "Klaar voor PvP",
			loc_selecting = "Blind aan het kiezen",
			loc_shop = "Shoppen",
			loc_playing = "Spelen ",
			current_seed = "Huidige seed: ",
			random = "Willekeurig",
			set_custom_seed = "Stel Aangepaste Seed In",
			reset = "Reset",
			mod_hash_warning = "Spelers hebben verschillende mods of mod versies! Dit kan problemen veroorzaken! Players have different mods or mod versions! This can cause problems!",
		},
	},
}
