return {
	descriptions = {
		Joker = {
			j_mp_defensive_joker = {
				name = "Curinga Defensivo",
				text = {
					"Este curinga ganha {C:chips}+#1#{} Fichas",
					"a cada {C:red,E:1}vida{} perdida nesta rodada",
					"{C:inactive}(No momento, {C:chips}+#2#{C:inactive} Fichas)",
				},
			},
			j_mp_skip_off = {
				name = "Caindo Fora",
				text = {
					"{C:blue}+#1#{} Mão(s) e {C:red}+#2#{} Descarte(s)",
					"por cada {C:attention}Blind{} ignorado,",
					"comparado ao seu {X:purple,C:white}Rival{}",
					"{C:inactive}(No momento, {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive})",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Bora Apostar",
				text = {
					"Chance de {C:green}#1# em #2#{} de ser destruído ao",
					"ser vendido. Caso contrário, ganha {X:mult,C:white} +X#3# {}",
					"{C:inactive}(Aumenta em {X:mult,C:white}+X#4#{C:inactive} após cada {C:attention}Blind de Chefe{C:inactive})",
					"{C:inactive}(No momento, {X:mult,C:white}X#5#{C:inactive} Multi)",
				},
			},
			j_mp_hanging_bad = {
				name = "A Química do Chad",
				text = {
					"Durante {C:attention}Blinds{} de {X:purple,C:white}Rival{}, a",
					"{C:attention}primeira{} carta usada para pontuar é",
					"{C:attention}enfraquecida{} para ambos os jogadores",
				},
			},
			j_mp_speedrun = {
				name = "SPEEDRUN",
				text = {
					"{C:attention}Triplica{} a sua pontuação total",
					"quando você usa todas as suas {C:blue}Mãos{}",
					"antes do seu {X:purple,C:white}Rival{} em uma {C:attention}Blind de Duelo{}",
				},
			},
			j_broken = {
				name = "QUEBRADA",
				text = {
					"Está carta está quebrada ou ainda",
					"não foi implementada na versão",
					"atual de um mod que você ativou.",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Asteroide",
				text = {
					"Elimina #1# nível da",
					"{C:legendary,E:1}mão de pôquer{}",
					"mais alta do seu",
					"{X:purple,C:white}Rival{}",
				},
			},
		},
		Blind = {
			bl_pvp = {
				name = "Seu Rival",
				text = {
					"Enfrente outro jogador.",
					"Quem tiver mais fichas vence",
				},
			},
			bl_precision = {
				name = "Precisão",
				text = {
					"Enfrente outro jogador.",
					"O mais próximo da pontuação mínima vence",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Rival",
				text = {
					"{X:purple,C:white}#1#{}",
					"Seu único rival",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Multijogador",
		},
		dictionary = {
			singleplayer = "Um jogador",
			join_lobby = "Entrar em uma Sala",
			return_lobby = "Voltar para a Sala",
			reconnect = "Reconectar",
			create_lobby = "Criar uma Sala",
			start_lobby = "Criar a Sala",
			enemy_score = "Pontuação do inimigo",
			enemy_hands = "Mãos restantes (inimigo): ",
			coming_soon = "Em breve!",
			ready = "Pronto",
			unready = "Cancelar",
			wait_enemy = "Esperando o inimigo terminar...",
			lives = "Vidas",
			leave_lobby = "Sair da Sala",
			lost_life = "Perdeu uma vida",
			failed = "Falhou",
			defeat_enemy = "Derrotou o inimigo",
			total_lives_lost = " Total de vidas perdidas ($4 para cada)",
			attrition_name = "Atrito",
			attrition_desc = "Os jogadores competem entre si em toda rodada de chefe e quem tiver menos pontos perde uma vida.",
			showdown_name = "Confronto",
			showdown_desc = "Ambos os jogadores jogam 3 Antes normais, depois jogam uma Ante onde quem pontuar mais em cada rodada vence.",
			draft_name = "Draft",
			draft_desc = "Os jogadores usam o Baralho Evolutivo do mod Balatro Draft, onde cada um recebe uma Marca de Draft após cada Blind de Duelo.",
			draft_req = "Requer o mod Balatro Draft",
			monty_special_name = "O Especial do Dr. Monty",
			monty_special_desc = "Um modo de jogo projetado pelo @dr_monty_the_snek no servidor do Discord. Tente jogar para descobrir o que é! (O modo de jogo muda a cada atualização pequena)",
			precision_name = "Precisão",
			precision_desc = "Igual ao modo Atrito, mas quem estiver mais próximo da pontuação mínima vence os Blinds de Duelo (e não quem tiver mais pontos).",
			royale_name = "Batalha Real",
			royale_desc = "Modo Atrito, mas com até 8 jogadores e apenas 1 vida.",
			vanilla_plus_name = "Padrão+",
			vp_desc = "Quem falhar em uma rodada primeiro perde. Sem Blinds de Duelo.",
			enter_lobby_code = "Insira o código da sala",
			join_clip = "Colar da área de transferência",
			username = "Nome:",
			enter_username = "Insira um nome",
			join_discord = "Entre no ",
			discord_name = "Servidor do Discord do Balatro Multiplayer",
			discord_msg = "Você poderá relatar erros e encontrar gente para jogar",
			enter_to_save = "Aperte Enter para salvar",
			in_lobby = "Na sala",
			connected = "Conectado",
			warn_service = "AVISO: Não foi possível encontrar o serviço Multiplayer",
			set_name = "Defina o seu nome de usuário no menu principal! (Mods > Multiplayer > Config)",
			start = "INICIAR",
			wait_for = "AGUARDANDO",
			host_start = "O INÍCIO DO JOGO",
			players = "OS JOGADORES",
			lobby_options_cap = "OPÇÕES DA SALA",
			lobby_options = "Opções da Sala",
			copy_clipboard = "Copiar para a área de transferência",
			connect_player = "Jogadores Conectados:",
			view_code = "VER CÓDIGO",
			leave = "SAIR",
			opts_only_host = "Apenas o criador da sala pode mudar estas opções",
			opts_cb_money = "Dar $ a cada vida perdida",
			opts_no_gold_on_loss = "Não ganhar recompensas de blind se perder uma rodada",
			opts_death_on_loss = "Perder uma vida se perder uma rodada que não for de duelo",
			opts_start_antes = "Antes Iniciais",
			opts_diff_seeds = "Todos os jogadores têm seeds diferentes",
			opts_lives = "Vidas",
			opts_gm = "Modos de Jogo",
			bl_or = "ou",
			bl_life = "Vida",
			bl_death = "Morte",
			lobby = "Sala",
			return_to = "Voltar para a",
			enemy_loc_1 = "Localização do",
			enemy_loc_2 = "inimigo",
			loc_ready = "Pronto para duelar",
			loc_selecting = "Escolhendo um blind",
			loc_shop = "Comprando",
			loc_playing = "Jogando ",
			current_seed = "Seed atual: ",
			random = "Aleatória",
			reset = "Redefinir",
			set_custom_seed = "Personalizar",
			mod_hash_warning = "Os jogadores possuem mods ou versões de mods diferentes! Isso pode dar problemas!",
			lobby_choose_deck = "BARALHO",
			opts_player_diff_deck = "Os jogadores possuem baralhos diferentes",
		},
	},
}
