-- Localization by @KilledByLava, @FaLNioNe, @sidmeierscivilizationv and @astryder75 on discord
return {
	descriptions = {
		Joker = {
			j_mp_defensive_joker = {
				name = "Защитный джокер",
				text = {
					"{C:chips}+#1#{} шт. фишек",
					"за каждую потерянную",
					"{C:red,E:1}жизнь{} в этом забеге",
					"{C:inactive}(Сейчас: {C:chips}+#2#{C:inactive} шт. фишек)",
				},
			},
			j_mp_skip_off = {
				name = "Пропускнофф",
				text = {
					"{C:blue}+#1#{} Рука и {C:red}+#2#{} Сброс за каждую разницу",
					"пропущенных {C:attention}Блайндов{}",
					"по сравнению с вашим {X:purple,C:white}Соперником{}",
					"{C:inactive}(Сейчас: {C:blue}+#3#{C:inactive}/{C:red}+#4#{C:inactive})",
				},
			},
			j_mp_lets_go_gambling = {
				name = "Крутите барабан",
				text = {
					"{C:green}#1# к #2#{} шанс уничтожиться при продаже",
					"иначе получает {X:mult,C:white} +X#3# {} множ.",
					"{C:inactive}(Рост увеличивается на {X:mult,C:white}+X#4#",
					"{C:inactive}после каждого {C:attention}Босс-блайнда{C:inactive})",
					"{C:inactive}(Сейчас: {X:mult,C:white}X#5#{C:inactive} множ.)",
				},
			},
			j_mp_hanging_bad = {
				name = "Первый блин комом",
				text = {
					"Во время {C:attention}сражения с{} {X:purple,C:white}Соперником{}",
					"{C:attention}первая{} сыгранная карта",
					"{C:attention}ослаблена{} для обоих игроков",
				},
			},
			j_mp_speedrun = {
				name = "СПИДРАН",
				text = {
					"{C:attention}Утраивает{} ваш окончательный счёт",
					"при трате всех {C:blue}Рук{} быстрее",
					"вашего {X:purple,C:white}Соперника{} на {C:attention}ПвП-блайнде{}",
				},
			},
			j_broken = {
				name = "Ошибка",
				text = {
					"Эта карта либо сломана",
					"либо ещё не добавлена в",
					"данной версии мода.",
				},
			},
		},
		Planet = {
			c_mp_asteroid = {
				name = "Астероид",
				text = {
					"Убирает #1# уровень с",
					"самой прокачанной {C:legendary,E:1}комбинации{}",
					"вашего {X:purple,C:white}Соперника{}",
				},
			},
		},
		Blind = {
			bl_pvp = {
				name = "Ваш Соперник",
				text = {
					"Сражение с вашим Соперником,",
					"игрок с наибольшим счётом побеждает",
				},
			},
			bl_precision = {
				name = "Точность",
				text = {
					"Сражение с вашим Соперником,",
					"ближайший к цели по очкам побеждает",
				},
			},
		},
		Other = {
			current_nemesis = {
				name = "Соперник",
				text = {
					"{X:purple,C:white}#1#{}",
					"Ваш один-единственный Соперник",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Сетевая игра",
		},
		dictionary = {
			singleplayer = "Одиночная Игра",
			join_lobby = "Подключиться к лобби",
			return_lobby = "Вернуться в лобби",
			reconnect = "Переподключиться",
			create_lobby = "Создать лобби",
			start_lobby = "Начать игру",
			enemy_score = "Счёт соперника",
			enemy_hands = "Количество рук у соперника: ",
			coming_soon = "Скоро!",
			ready = "Приготовиться",
			unready = "Отменить",
			wait_enemy = "Ждём, пока соперник закончит...",
			lives = "Жизни",
			leave_lobby = "Выйти из лобби",
			lost_life = "Потеряна жизнь",
			failed = "Поражение",
			defeat_enemy = "Соперник побеждён",
			total_lives_lost = " Всего потеряно жизней (По $4 каждая)",
			attrition_name = "Истощение",
			attrition_desc = "Каждый Босс-блайнд - соревнование, где игрок с меньшим счётом теряет жизнь.",
			-- New stuff here
			showdown_name = "Столкновение",
			showdown_desc = "Оба игрока играют 3 обычных анте, потом они играют анте, в котором игроки соревнуются каждый раунд.",
			draft_name = "Подготовка",
			draft_desc = "Игроки играют особую колоду с мода Draft, в котором они получают особый тег после каждого ПвП-блайнда.",
			draft_req = "Требует мод Draft",
			monty_special_name = "Спец. режим Dr. Monty",
			monty_special_desc = "Режим с правилами от @dr_monty_the_snek из дискорд сервера. Думаю, вам предстоить узнать их самим! (Режим меняется каждое мелкое обновление)",
			precision_name = "Точность",
			precision_desc = "Истощение, но побеждает тот, кто ближе всего к цели по очкам в ПвП-блайндах (вместо того, у кого больше всего счёт).",
			-- New stuff ends here
			royale_name = "Королевская Битва",
			royale_desc = "Истощение, но играют до 8 игроков и каждый игрок имеет только одну жизнь.",
			vanilla_plus_name = "Ванилла+",
			vp_desc = "Первый игрок, проигравший раунд, проигрывает, ПвП-блайндов нет.",
			enter_lobby_code = "Введите код лобби",
			join_clip = "Вставить код",
			username = "Имя:",
			enter_username = "Введите имя",
			join_discord = "Присоединяйтесь к ",
			discord_name = "Дискорд Серверу Balatro Multiplayer",
			discord_msg = "Там вы можете сообщать об ошибках и находить игроков",
			enter_to_save = "Нажмите ВВОД, чтобы сохранить",
			in_lobby = "В лобби",
			connected = "Подключено к сервисам",
			warn_service = "ПРЕДУПРЕЖДЕНИЕ: Не получилось найти сервисы",
			set_name = "Введите своё имя в главном меню! (Mods > Multiplayer > Config)",
			start = "НАЧАТЬ",
			wait_for = "ЖДЁМ",
			host_start = "НАЧАЛА ИГРЫ",
			players = "ИГРОКОВ",
			lobby_options_cap = "ПАРАМЕТРЫ ЛОББИ",
			lobby_options = "Параметры лобби",
			copy_clipboard = "Скопировать",
			connect_player = "Игроки в лобби:",
			view_code = "УВИДЕТЬ КОД",
			leave = "ВЫЙТИ",
			opts_only_host = "Только ведущий может менять эти настройки",
			opts_cb_money = "Давать доп. золото при потери жизни",
			opts_no_gold_on_loss = "Не давать золото при поражении раунда",
			opts_death_on_loss = "Терять жизнь при поражении не ПвП-блайнда",
			opts_start_antes = "Количество анте до ПвП-блайндов",
			opts_diff_seeds = "Игроки имеют разные сиды",
			opts_lives = "Количество жизней",
			opts_gm = "Настройки игры",
			bl_or = "или",
			bl_life = "Жизнь",
			bl_death = "Смерть",
			lobby = "Лобби",
			return_to = "Вернуться в",
			enemy_loc_1 = "Статус",
			enemy_loc_2 = "соперника",
			loc_ready = "Готов к сражению",
			loc_selecting = "Выбирает Блайнд",
			loc_shop = "В магазине",
			loc_playing = "Против ",
			current_seed = "Сид лобби: ",
			random = "Случайный",
			set_custom_seed = "Использовать Свой",
			reset = "Сбросить",
			mod_hash_warning = "У игроков разные моды либо разные версии модов! Это может привести к ошибкам!",
			-- New stuff here
			lobby_choose_deck = "КОЛОДА",
			opts_player_diff_deck = "Игроки имеют разные колоды",
		},
	},
}
