return {
	descriptions = {
		Blind = {
			bl_pvp = {
				name = "Đối thủ của bạn",
				text = {
					"Gặp một người chơi khác,",
					"người nhiều xu nhất dành chiến thắng",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Chơi Mạng",
		},
		dictionary = {
			singleplayer = "Chơi Đơn",
			join_lobby = "Vào Phòng",
			return_lobby = "Quay lại Phòng",
			reconnect = "Kết nối lại",
			create_lobby = "Tạo Phòng",
			start_lobby = "Mở Phòng",
			enemy_score = "Điểm Đối thủ hiện tại",
			enemy_hands = "Tay bài còn lại của Đối thủ: ",
			coming_soon = "Sắp ra mắt!",
			ready = "Sẵn sàng",
			unready = "Huỷ sẵn sàng",
			wait_enemy = "Đang chờ đối thủ hoàn thành vòng chơi...",
			lives = "Mạng",
			leave_lobby = "Rời Phòng",
			lost_life = "Mất một mạng",
			failed = "Thất bại",
			defeat_enemy = "Đánh bại Đối thủ",
			total_lives_lost = " Tổng Mạng đã mất ($4 mỗi mạng)",
			attrition_name = "Hao Mòn",
			attrition_desc = "Mọi vòng trùm sẽ là cuộc đấu giữa người chơi, ai thấp điểm hơn sẽ mất một mạng.",
			draft_name = "Tự Chọn",
			draft_desc = "Cả hai người chơi cùng đánh 3 mốc cược bình thường, sau đó họ cùng đánh một bàn nơi ai cao điểm hơn sẽ giành chiến thắng.",
			royale_name = "Sinh Tồn",
			royale_desc = "Thể thức Hao Mòn, nhưng thay vì đó sẽ có 8 người chơi và mỗi người chơi chỉ có một mạng duy nhất.",
			vanilla_plus_name = "Cơ Bản+",
			vp_desc = "Ai thua round trước sẽ là người thua cuộc, không có cược Đối Đầu.",
			enter_lobby_code = "Nhập Mã Phòng",
			join_clip = "Dán từ Bộ nhớ tạm",
			username = "Tên:",
			enter_username = "Nhập tên",
			join_discord = "Tham gia ",
			discord_name = "Máy chủ Discord Balatro Multiplayer",
			discord_msg = "Bạn có thể báo cáo lỗi cũng như tìm người chơi cùng ở đó",
			enter_to_save = "Nhấn enter để lưu",
			in_lobby = "Trong phòng",
			connected = "Đã kết nối tới Máy chủ",
			warn_service = "CHÚ Ý: Không thể tìm thấy Máy chủ Multiplayer",
			set_name = "Đặt tên của bạn trong menu chính! (Mods > Multiplayer > Tuỳ Chọn)",
			start = "BẮT ĐẦU",
			wait_for = "ĐANG CHỜ",
			host_start = "CHỦ PHÒNG BẮT ĐẦU",
			players = "NGƯỜI CHƠI",
			lobby_options_cap = "TUỲ CHỈNH PHÒNG",
			lobby_options = "Tuỳ chỉnh Phòng",
			copy_clipboard = "Sao chép vào Bộ nhớ tạm",
			connect_player = "Người chơi đã Kết nối:",
			view_code = "XEM CODE",
			leave = "THOÁT",
			opts_only_host = "Chỉ có Chủ Phòng mới có thể chỉnh sửa những tuỳ chỉnh này",
			opts_cb_money = "Bù $ cho người chơi khi họ mất mạng",
			opts_no_gold_on_loss = "Không nhận phần thưởng cược khi thua vòng",
			opts_death_on_loss = "Mất mạng khi thua vòng đấu với người",
			opts_start_antes = "Bàn khởi đầu",
			opts_diff_seeds = "Người chơi có seed khác nhau",
			opts_lives = "Số mạng",
			opts_gm = "Tinh chỉnh Chế độ chơi",
			bl_or = "hoặc",
			bl_life = "Sống",
			bl_death = "Chết",
			lobby = "Phòng",
			return_to = "Trở về",
			enemy_loc_1 = "Vị trí",
			enemy_loc_2 = "Đối thủ",
			loc_ready = "Sẵn sàng",
			loc_selecting = "Đang chọn Mốc Cược",
			loc_shop = "Đang đi chợ",
			loc_playing = "Đang đánh ",
			current_seed = "Seed hiện tại: ",
			random = "Ngẫu nhiên",
			reset = "Đặt lại",
			set_custom_seed = "Đặt seed tuỳ chỉnh",
			mod_hash_warning = "Người chơi đang có mod hoặc phiên bản mod khác nhau, điều này có thể gây vấn đề khi chơi!",
		},
	},
}
