-- Localization by CUexter on GitHub
return {
	descriptions = {
		Blind = {
			bl_pvp = {
				name = "你的对手",
				text = {
					"在所有玩家中，",
					"得分最多的人赢",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "多人游戏",
		},
		dictionary = {
			singleplayer = "单人游戏",
			join_lobby = "加入大厅",
			return_lobby = "返回大厅",
			reconnect = "重新连接",
			desc = "让你可以与其他人对战",
			create_lobby = "建立大厅",
			start_lobby = "开放大厅",
			enemy_score = "对手现在的分数",
			enemy_hands = "对手剩余的手牌數",
			coming_soon = "即将推出",
			ready = "准备下一回合",
			unready = "取消准备",
			wait_enemy = "等待对手完成...",
			lives = "剩余生命",
			leave_lobby = "离开大厅",
			lost_life = "失去了一生命",
			failed = "败了",
			defeat_enemy = "击败对手",
			total_lives_lost = "一共失去的生命（每条命 $4）",
			attrition_name = "消耗战",
			attrition_desc = "每个Boss回合都是玩家之间的比賽, 分数较低的玩家会失去一生命",
			draft_name = "选拔赛",
			draft_desc = "玩家双方会玩三次正常的底注, 然后他们会玩一次底注, 每回合分数较低的人会失去一条生命",
			royale_name = "大乱斗",
			royale_desc = "类似消耗战，但有八个玩家且每人只有一条命",
			vanilla_plus_name = "经典+",
			vp_desc = "第一个输的人就输，没有PVP的盲注",
			enter_lobby_code = "输入大厅代碼",
			join_clip = "从剪贴版输入",
			username = "用户名：",
			enter_username = "输入用户名",
			join_discord = "加入",
			discord_name = "Balatro多人-Discord频道",
			discord_msg = "你可以在那里报告找到的bugs并找到人陪你玩",
			enter_to_save = "按Enter保存",
			in_lobby = "在大厅",
			connected = "服务已连接",
			warn_service = "警告：无法找到多人服务器",
			set_name = "可以在主菜单设置自己的名字（Mods > Multiplayer）",
			start = "开始",
			wait_for = "等待",
			host_start = "大厅主开始",
			players = "其他玩家",
			lobby_options = "大厅設置",
			lobby_options_cap = "大厅設置",
			copy_clipboard = "复制到剪贴版",
			connect_player = "已连接玩家：",
			view_code = "查看代碼",
			leave = "离开",
			opts_only_host = "只有大厅主能改这些设置",
			opts_cb_money = "死后会给钱重新开始",
			opts_no_gold_on_loss = "输了回合则失去那个盲注的钱",
			opts_death_on_loss = "如果非PvP回合输了会失去一条生命",
			opts_start_antes = "一开始正常底注数目",
			opts_diff_seeds = "玩家有不同的SEED",
			opts_lives = "生命数",
			opts_gm = "模式修改效果",
			bl_or = "或",
			bl_life = "生",
			bl_death = "死",
			lobby = "大厅",
			return_to = "返回",
		},
	},
}
