-- Localization by @xphrogx on discord
return {
	descriptions = {
		Joker = {
			j_broken = {
				name = "Defekt",
				text = {
					"Diese Karte is entweder",
					"defekt oder nicht verfügbar in der",
					"Version der Mod die benutzt wird.",
				},
			},
		},
		Blind = {
			bl_pvp = {
				name = "Dein Erzfeind",
				text = {
					"Spiel gegen dein Erzfeind,",
					"Höste Punktzahl gewinnt",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Mehrspieler",
		},
		dictionary = {
			singleplayer = "Einzelspieler",
			join_lobby = "Lobby beitreten",
			return_lobby = "Zurück zur lobby",
			reconnect = "Widerverbinden",
			create_lobby = "Lobby herstellen",
			start_lobby = "Lobby starten",
			enemy_score = "Dein Gegners Punktzahl",
			enemy_hands = "Gegners übrige Hände: ",
			coming_soon = "Kommt bald!",
			ready = "Bereit",
			unready = "Nicht bereit",
			wait_enemy = "Warte auf dein Gegner...",
			lives = "Leben",
			leave_lobby = "Lobby verlassen",
			lost_life = "Ein leben verloren",
			failed = "Verloren",
			defeat_enemy = "Gegner besiegt",
			total_lives_lost = "Gesamtzahl an verloren Leben ($4 Pro Leben)",
			attrition_name = "Standard",
			attrition_desc = "Jeder Boss Blind is ein kampf gegen deine Gegner. Wer die niedrigste Punktzahl hat verliert ein Leben",
			draft_name = "Draft",
			draft_desc = "Beide spieler spielen 3 Antes, dann spielen sie eine Ante wo jede Runde der Spieler mit der hösten Punktzahl gewinnt.",
			royale_name = "Battle Royale",
			royale_desc = "Standard, aber ihr seid bis zu 8 Spieler und jeder hat nur 1 Leben.",
			vanilla_plus_name = "Vanilla+",
			vp_desc = "Der Erste spieler der eine rounde verliert verliert das spiel, keine PvP Blinds.",
			enter_lobby_code = "Lobby Code eingeben",
			join_clip = "Einfügen von der Zwischenablage",
			username = "Benutzername:",
			enter_username = "Benutzername eingeben",
			join_discord = "Finde uns im",
			discord_name = "Balatro Mehrspieler Discord Server",
			discord_msg = "Du kannst Bugs hier reporten und andere Mitspieler finden",
			enter_to_save = "Drück Enter zum speichern",
			in_lobby = "In Der Lobby",
			connected = "Verbindung zum Service hergestellt",
			warn_service = "WARNUNG: Mehrspieler service konnte nicht gefunden werden",
			set_name = "Setz dein Benutzername in der Config im Hauptmenü! (Mods > Multiplayer > Config)",
			start = "START",
			wait_for = "WARTE AUF",
			host_start = "DEN HOST",
			players = "ANDERE SPIELER",
			lobby_options_cap = "LOBBY OPTIONEN",
			lobby_options = "Lobby Optionen",
			copy_clipboard = "Zur Zwischenablage kopieren",
			connect_player = "Verbundene Spieler:",
			view_code = "CODE ZEIGEN",
			leave = "VERLASSEN",
			opts_only_host = "Nur der Host kann diese Einstellungen ändern",
			opts_cb_money = "Gib comeback $ wenn ein Leben verloren ist",
			opts_no_gold_on_loss = "Gib keine Blind Belohnung wenn eine runde verloren wurde",
			opts_death_on_loss = "Verlier ein Leben wehnn eine nicht-PvP runde verloren wurde",
			opts_start_antes = "Starter Antes",
			opts_diff_seeds = "Spieler haben unterschiedliche seeds",
			opts_lives = "Leben",
			opts_gm = "Spiel Modifikationen",
			bl_or = "oder",
			bl_life = "Leben",
			bl_death = "Sterben",
			lobby = "Lobby",
			return_to = "Zurück zur",
			enemy_loc_1 = "Gegner",
			enemy_loc_2 = "Standort",
			loc_ready = "Bereit für PvP",
			loc_selecting = "Eine Blind am auswählen",
			loc_shop = "Einkaufen",
			loc_playing = "Spielen",
			current_seed = "Aktueller seed: ",
			random = "Zufällig",
			reset = "Neustart",
			set_custom_seed = "Setzt eigenen Seed fest",
			mod_hash_warning = "Spieler haben andere Mods oder unterschidliche Mod versionen! Dies kann probleme verursachen!",
		},
	},
}
