-- Localization by @KilledByLava, @FaLNioNe, and @astryder75 on discord
return {
	Joker = {
		j_broken = {
			name = "Ошибка",
			text = {
				"Эта карта либо сломана",
				"либо ещё не добавлена в",
				"данной версии мода.",
			},
		},
	},
	descriptions = {
		Blind = {
			bl_pvp = {
				name = "Ваш соперник",
				text = {
					"Сражение с вашим соперником,",
					"наибольший счёт побеждает",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "Сетевая игра",
		},
		dictionary = {
			singleplayer = "Одиночная Игра",
			join_lobby = "Подключиться к лобби",
			return_lobby = "Вернуться в лобби",
			reconnect = "Переподключиться",
			create_lobby = "Создать лобби",
			start_lobby = "Начать игру",
			enemy_score = "Счёт соперника",
			enemy_hands = "Количество рук у соперника: ",
			coming_soon = "Скоро!",
			ready = "Приготовиться",
			unready = "Отменить",
			wait_enemy = "Ждём, пока соперник закончит...",
			lives = "Жизни",
			leave_lobby = "Выйти из лобби",
			lost_life = "Потеряна жизнь",
			failed = "Поражение",
			defeat_enemy = "Соперник побеждён",
			total_lives_lost = " Всего потеряно жизней (По $4 каждая)",
			attrition_name = "Истощение",
			attrition_desc = "Каждый босс-блайнд - соревнование, где игрок с меньшим счётом теряет жизнь.",
			draft_name = "Подготовка",
			draft_desc = "Оба игрока играют 3 обычных анте, потом они играют анте, в котором игроки соревнуются каждый раунд.",
			royale_name = "Королевская Битва",
			royale_desc = "Истощение, но играют до 8 игроков и каждый игрок имеет только одну жизнь.",
			vanilla_plus_name = "Ванилла+",
			vp_desc = "Первый игрок, проигравший раунд, проигрывает, ПвП блайндов нет.",
			enter_lobby_code = "Введите код лобби",
			join_clip = "Вставить код",
			username = "Имя:",
			enter_username = "Введите имя",
			join_discord = "Присоединяйтесь к ",
			discord_name = "Дискорд Серверу Balatro Multiplayer",
			discord_msg = "Там вы можете сообщать об ошибках и находить игроков",
			enter_to_save = "Нажмите ВВОД, чтобы сохранить",
			in_lobby = "В лобби",
			connected = "Подключено к сервисам",
			warn_service = "ПРЕДУПРЕЖДЕНИЕ: Не получилось найти сервисы",
			set_name = "Введите своё имя в главном меню! (Mods > Multiplayer > Config)",
			start = "НАЧАТЬ",
			wait_for = "ЖДЁМ",
			host_start = "НАЧАЛА ИГРЫ",
			players = "ИГРОКОВ",
			lobby_options_cap = "ПАРАМЕТРЫ ЛОББИ",
			lobby_options = "Параметры лобби",
			copy_clipboard = "Скопировать",
			connect_player = "Игроки в лобби:",
			view_code = "УВИДЕТЬ КОД",
			leave = "ВЫЙТИ",
			opts_only_host = "Только ведущий может менять эти настройки",
			opts_cb_money = "Давать доп. золото при потери жизни",
			opts_no_gold_on_loss = "Не давать золото при поражении раунда",
			opts_death_on_loss = "Терять жизнь при поражении не-ПвП блайнда",
			opts_start_antes = "Количество анте до ПвП блайндов",
			opts_diff_seeds = "Игроки имеют разные сиды",
			opts_lives = "Количество жизней",
			opts_gm = "Настройки игры",
			bl_or = "или",
			bl_life = "Жизнь",
			bl_death = "Смерть",
			lobby = "Лобби",
			return_to = "Вернуться в",
			enemy_loc_1 = "Статус",
			enemy_loc_2 = "соперника",
			loc_ready = "Готов к ПвП",
			loc_selecting = "Выбирает Блайнд",
			loc_shop = "В магазине",
			loc_playing = "Против ",
			current_seed = "Сид лобби: ",
			random = "Случайный",
			set_custom_seed = "Использовать Свой",
			reset = "Сбросить",
			mod_hash_warning = "У игроков разные моды либо разные версии модов! Это может привести к ошибкам!",
			lobby_choose_deck = "КОЛОДА",
			opts_player_diff_deck = "Игроки имеют разные колоды",
		},
	},
}
