-- Localization by CUexter on GitHub
return {
	descriptions = {
		Blind = {
			bl_pvp = {
				name = "你的對手",
				text = {
					"面對其他玩家，",
					"得分最多的人贏",
				},
			},
		},
	},
	misc = {
		challenge_names = {
			c_multiplayer_1 = "多人遊戲",
		},
		dictionary = {
			singleplayer = "單人遊戲",
			join_lobby = "加入大廳",
			return_lobby = "返回大廳",
			reconnect = "重新連線",
			desc = "令你可以與其他人對戰",
			create_lobby = "建立大廳",
			start_lobby = "開放大廳",
			enemy_score = "現在對手的分數",
			enemy_hands = "對手剩餘的手牌數",
			coming_soon = "即將推出",
			ready = "準備下一回合",
			unready = "取消準備",
			wait_enemy = "等待對手完成...",
			lives = "剩餘命數",
			leave_lobby = "離開大廳",
			lost_life = "失去了一條命",
			failed = "失敗了",
			defeat_enemy = "擊敗對手",
			total_lives_lost = "總共失去的命數（每條命 $4）",
			attrition_name = "消耗戰",
			attrition_desc = "每個Boss回合都是玩家之間的比賽, 分數較低的玩家會失去一條命",
			draft_name = "選拔戰",
			draft_desc = "雙方玩家會玩三次正常的底注, 然後他們會玩一次底注, 每回合分數較低的人會失去一條命",
			royale_name = "大亂鬥",
			royale_desc = "類似消耗戰，但有八個玩家且每人只有一條命",
			vanilla_plus_name = "經典+",
			vp_desc = "第一個輸的人就輸，沒有PVP的盲注",
			enter_lobby_code = "輸入大廳代碼",
			join_clip = "從剪貼簿貼上",
			username = "用戶名稱：",
			enter_username = "輸入用戶名稱",
			join_discord = "加入",
			discord_name = "Balatro多人Discord",
			discord_msg = "你可以在那裡報告找到的bugs並找到人陪你玩",
			enter_to_save = "按Enter保存",
			in_lobby = "在大廳",
			connected = "服務已連接",
			warn_service = "警告：無法找到多人伺服器",
			set_name = "可以在主選單設置自己的名字（Mods > Multiplayer）",
			start = "開始",
			wait_for = "等待",
			host_start = "大廳主開始",
			players = "其他玩家",
			lobby_options = "大廳設置",
			lobby_options_cap = "大廳設置",
			copy_clipboard = "複製到剪貼簿",
			connect_player = "已連接玩家：",
			view_code = "查看代碼",
			leave = "離開",
			opts_only_host = "只有大廳主能改這些設置",
			opts_cb_money = "死後會給錢重新開始",
			opts_no_gold_on_loss = "輸了回合會失去那個盲注的錢",
			opts_death_on_loss = "如果非PvP回合輸了會失去一條命",
			opts_start_antes = "一開始正常底注數目",
			opts_diff_seeds = "玩家有不同的SEED",
			opts_lives = "命數",
			opts_gm = "模式修改效果",
			bl_or = "或",
			bl_life = "生",
			bl_death = "死",
			lobby = "大廳",
			return_to = "返回",
		},
	},
}
