name: Create Release

on:
  push:
    tags:
      - "*.*.*" # Matches tags like 1.0.0, 2.3.4, etc.
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "::set-output name=version::$VERSION"

      - name: Download macOS build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts-macos-latest
          path: ./release/Multiplayer/macos

      - name: Download Windows build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts-windows-latest
          path: ./release/Multiplayer/windows

      - name: Prepare release assets
        env:
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
          CONFIG_PORT: ${{ secrets.CONFIG_PORT }}
        run: |
          mkdir -p release/Multiplayer
          cp -r Multiplayer/* release/Multiplayer/
          rm release/Multiplayer/example.Config.lua

          # Create the config.lua file
          echo "----------------------------------------------" > release/Multiplayer/config.lua
          echo "------------MOD CONFIG------------------------" >> release/Multiplayer/config.lua
          echo "" >> release/Multiplayer/config.lua
          echo "Config = {}" >> release/Multiplayer/config.lua
          echo "" >> release/Multiplayer/config.lua
          echo "Config.URL = '${CONFIG_URL}'" >> release/Multiplayer/config.lua
          echo "Config.PORT = ${CONFIG_PORT}" >> release/Multiplayer/config.lua
          echo "" >> release/Multiplayer/config.lua
          echo "return Config" >> release/Multiplayer/config.lua
          echo "" >> release/Multiplayer/config.lua
          echo "----------------------------------------------" >> release/Multiplayer/config.lua
          echo "------------MOD CONFIG END--------------------" >> release/Multiplayer/config.lua

          # Create the Version.lua file with the version number
          VERSION=${{ steps.extract_version.outputs.version }}
          echo "return \"$VERSION\"" > release/Multiplayer/Version.lua

          # Zip the Multiplayer directory with the desired name
          cd release
          zip -r Multiplayer-beta-$VERSION.zip Multiplayer
          cd ..

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          release_name: v${{ steps.extract_version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload macOS DLL
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/Multiplayer/macos/multiplayer.dylib
          asset_name: multiplayer-macos-${{ steps.extract_version.outputs.version }}.dylib
          asset_content_type: application/octet-stream

      - name: Upload Windows DLL
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/Multiplayer/windows/multiplayer.dll
          asset_name: multiplayer-windows-${{ steps.extract_version.outputs.version }}.dll
          asset_content_type: application/octet-stream

      - name: Upload beta zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/Multiplayer-beta-${{ steps.extract_version.outputs.version }}.zip
          asset_name: Multiplayer-beta-${{ steps.extract_version.outputs.version }}.zip
          asset_content_type: application/zip
